### ISSUE TITLE
Ata de reunião 12/04

### ISSUE THREAD

**Issue by paulatalim** [ICEI-PUC-Minas-PMG-EC-GPS/pmg-ec-2024-01-gps-92470101-time-grp2#13]

**Comment by LeoPizani** [comment]
[ata-reuniao_2024-04-12.pdf](https://github.com/ICEI-PUC-Minas-PMG-EC-GPS/pmg-ec-2024-01-gps-92470101-time-grp2/files/14964552/ata-reuniao_2024-04-12.pdf)
