### ISSUE TITLE
Ata de reunião 22/03

### ISSUE THREAD

**Issue by gabrielcecconello** [ICEI-PUC-Minas-PMG-EC-GPS/pmg-ec-2024-01-gps-92470101-time-grp2#14]

**Comment by LeoPizani** [comment]
[ata-reuniao_2024-03-22.pdf](https://github.com/ICEI-PUC-Minas-PMG-EC-GPS/pmg-ec-2024-01-gps-92470101-time-grp2/files/14729221/ata-reuniao_2024-03-22.pdf)
