### ISSUE TITLE
Ata de Reunião 26/04

### ISSUE THREAD

**Issue by paulatalim** [ICEI-PUC-Minas-PMG-EC-GPS/pmg-ec-2024-01-gps-92470101-time-grp2#17]

**Comment by LeoPizani** [comment]
[ata-reuniao_2024-04-26.pdf](https://github.com/ICEI-PUC-Minas-PMG-EC-GPS/pmg-ec-2024-01-gps-92470101-time-grp2/files/15136011/ata-reuniao_2024-04-26.pdf)
