### ISSUE TITLE
Ata de reuniao 15/03

### ISSUE THREAD

**Issue by paulatalim** [ICEI-PUC-Minas-PMG-EC-GPS/pmg-ec-2024-01-gps-92470101-time-grp2#4]

**Comment by LeoPizani** [comment]
[AtadeReuniao1503.pdf](https://github.com/ICEI-PUC-Minas-PMG-EC-GPS/pmg-ec-2024-01-gps-92470101-time-grp2/files/14621588/AtadeReuniao1503.pdf)
